module.exports = {
  apps: [
    {
      name: 'client-web',
      script: 'npm',
      args: 'start',
      cwd: '/opt/client-web',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      merge_logs: true,
    },
    {
      name: 'graph-sync-worker',
      script: 'npx',
      args: 'tsx src/workers/graph-sync-worker.ts',
      cwd: '/opt/client-web',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/graph-sync-error.log',
      out_file: './logs/graph-sync-out.log',
      merge_logs: true,
    },
    {
      name: 'message-pipeline-worker',
      script: 'npx',
      args: 'tsx src/workers/message-pipeline-worker.ts',
      cwd: '/opt/client-web',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/message-pipeline-error.log',
      out_file: './logs/message-pipeline-out.log',
      merge_logs: true,
    },
  ],
}
